# Generated by Django 4.2.6 on 2023-12-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0009_alter_memory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
