# Generated by Django 4.2.6 on 2023-11-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0004_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='memory',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
