# Generated by Django 4.2.6 on 2023-11-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0006_remove_memory_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
